# Generated by Django 5.0.4 on 2024-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_group_alter_user_age_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, choices=[('company', 'Компания'), ('user', 'Пользователь')], null=True),
        ),
    ]
