# Generated by Django 5.0.4 on 2024-05-09 10:16

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('cities', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('offer', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('salary', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cities.cities')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='countries.countries')),
            ],
        ),
    ]
